// Resume content
window.PORTFOLIO_DATA = {
  name: "Naama Mendes Jr.",
  monogram: "NM",
  email: "naamamendesjr@gmail.com",
  phone: "(321) 276-8858",
  tagline: "Product leader building fintech and growth platforms used by millions.",
  intro: "I'm a product leader with a decade of experience scaling B2B and B2C platforms — from a payroll fintech I co‑founded and sold, to leading product at YC‑backed startups, to building, shipping and distributing a new vertical from 0 to 15% of revenue in 3 months at Tapcheck today. I work where data, design, and infrastructure meet — and I'm rebuilding how my team ships in the agent era.",

  works: [
    {
      id: "tapcheck-director",
      year: "2025 — Now",
      company: "Tapcheck",
      role: "Director of Product — Growth",
      category: "Earned Wage Access · 0→1 Vertical",
      headline: "Built, shipped, and distributed a new standalone vertical from 0 to 15% of revenue in 3 months — and rewired the org around Claude Code.",
      metrics: [
        { value: "0 → 15%", label: "of revenue in 3 months (new vertical)" },
        { value: "−35%", label: "Reduced loss rate" },
        { value: "6mo → 45d", label: "App rebuild time with Claude Code" },
        { value: "40+", label: "Cross‑functional team led" },
      ],
      bullets: [
        "Built, shipped, and distributed a new standalone vertical from 0 to 15% of revenue within 3 months.",
        "Redesigned product and engineering workflows around Claude Code — rebuilt a full app in 45 days versus the previous 6‑month baseline.",
        "Led and coached the product team on Claude Code adoption, enabling PMs to ship working prototypes directly to code without engineering intervention.",
        "Lead a 40+ person cross‑functional team (Sales, RevOps, Customer Success, three engineering pods) with clear OKRs and accountability frameworks.",
      ],
    },
    {
      id: "tapcheck-lead",
      year: "2024 — 2025",
      company: "Tapcheck",
      role: "Lead Product Manager — B2B Growth",
      category: "Distribution · Activation",
      headline: "Rewrote the distribution strategy and the activation funnel around real user friction.",
      metrics: [
        { value: "+45%", label: "User growth in 2 quarters" },
        { value: "5% → 21%", label: "Disbursement adoption per cycle" },
        { value: "−80%", label: "Customer incidents" },
        { value: "250+", label: "Payroll partners aligned" },
      ],
      bullets: [
        "Redesigned distribution strategy by identifying core user friction in employer onboarding — moved from direct permissioning to an automated onboarding process, enabling 45% user growth in two quarters.",
        "Launched a user‑centric disbursement service through behavioral data and user research, lifting adoption from 5% to 21% per payroll cycle by solving the time‑to‑value problem.",
        "Defined and tracked key metrics — user activation, transfer frequency, employer satisfaction — and used cohort analysis to identify optimization opportunities.",
        "Implemented a measurement framework that reduced customer incidents by 80% through proactive monitoring and alerting.",
        "Drove strategic partnerships with 250+ payroll providers through stakeholder alignment and negotiation.",
      ],
    },
    {
      id: "tapcheck-platform",
      year: "2023 — 2024",
      company: "Tapcheck",
      role: "Senior Product Manager — Platform & Integrations",
      category: "Infrastructure · Platform",
      headline: "API‑first integration platform behind the predictive earnings model.",
      metrics: [
        { value: "+7%", label: "Transfers via predicted earnings (ML)" },
        { value: "16d → 1d", label: "Partner onboarding time" },
      ],
      bullets: [
        "Led product discovery and implementation of an ML algorithm predicting employee earnings during each pay cycle, lifting transfers by 7%.",
        "Built an API‑first integration platform enabling rapid partner onboarding (16 days → 1 day), supporting business expansion strategy.",
        "Led infrastructure transformation, coordinating across engineering, DevOps, and business teams.",
      ],
    },
    {
      id: "cb-insights",
      year: "2022 — 2023",
      company: "CB Insights",
      role: "Senior Product Manager",
      category: "Market Intelligence · SaaS",
      headline: "Personalized onboarding and behavioral triggers, top to bottom of the funnel.",
      metrics: [
        { value: "+27%", label: "Trial → paid conversion" },
        { value: "59% → 75%", label: "Weekly active users" },
      ],
      bullets: [
        "Created personalized onboarding based on company data and user roles, improving conversion by 27%.",
        "Built a comprehensive analytics framework tracking weekly active users, feature adoption, and conversion funnels.",
        "Designed an alert and email engagement system that grew WAU from 59% to 75% via behavioral trigger optimization.",
        "Coordinated a cross‑functional growth team with Sales, Marketing, and RevOps to optimize the entire customer acquisition funnel.",
      ],
    },
    {
      id: "datlo",
      year: "2019 — 2022",
      company: "Datlo",
      role: "Chief Product Officer",
      category: "Geomarketing · YC W21",
      headline: "Y Combinator W21 — turned a consultancy into a Fortune‑500 SaaS platform.",
      metrics: [
        { value: "YC W21", label: "Investment secured" },
        { value: "+25%", label: "MoM growth, sustained" },
        { value: "20", label: "Person team built & led" },
        {
          type: "clients",
          label: "Enterprise clients served",
          logos: ["Cargill", "Bunge", "AB InBev"],
          note: "ML/AI platform optimizing point‑of‑sale throughput across Latin America's largest agribusiness and beverage operators.",
        },
      ],
      bullets: [
        "Led product transformation from consulting service to scalable B2B SaaS platform.",
        "ML/AI platform optimizing point‑of‑sale throughput — serving Cargill, Bunge, and AB InBev.",
        "Established data‑driven product development using usage analytics to guide feature prioritization and roadmap.",
        "Created an API strategy and security framework for enterprise clients handling sensitive sales and logistics data.",
        "Recruited and led a 20‑person team — designers, engineers, data scientists — through hypergrowth.",
        "Secured Y Combinator investment through compelling product demonstrations and market analysis.",
        "Delivered 25% month‑over‑month growth consistently through disciplined execution and customer feedback loops.",
      ],
    },
    {
      id: "valuu",
      year: "2016 — 2019",
      company: "Valuu",
      role: "CEO & Co‑Founder",
      category: "Payroll Fintech · Acquired",
      headline: "Payroll‑integrated financial platform — acquired by SWAP, a Brazilian unicorn fintech.",
      metrics: [
        { value: "$100M+", label: "Processed through the platform" },
        { value: "Acquired", label: "by SWAP — Brazilian unicorn" },
      ],
      bullets: [
        "Identified an underserved market in financial services — helping Brazilian companies pay out government‑mandated food stipends through debit cards.",
        "Designed an end‑to‑end fintech platform supporting verification, treasury, payment processing, and distribution — moving over $100M through the system.",
        "Built referral and engagement systems that drove consistent user adoption and platform growth.",
        "Acquired by SWAP, a Brazilian unicorn fintech, after demonstrating strong product‑market fit and payroll‑integrated financial leadership.",
        "Led the company from ideation to exit through strategic vision, team building, and execution excellence.",
      ],
    },
  ],

  clients: [
    "Cargill", "Bunge", "AB InBev", "iFood", "SWAP", "Y Combinator", "Tapcheck", "CB Insights",
  ],

  capabilities: [
    "Product Strategy & Marketplace Growth",
    "User Research & Experimentation (A/B, Cohort)",
    "Cross‑Functional Team Leadership & Agile",
    "Product Roadmap & Documentation",
    "Data Analytics & SQL (BigQuery, Looker, Tableau)",
    "UI/UX Optimization (Figma, Heatmaps, User Testing)",
    "Fintech & Payment Infrastructure",
    "Geographic Information Systems",
    "ML Predictive Algorithms",
  ],

  education: [
    { school: "Tera, Brazil", degree: "Master's in Product Management", year: "2019", note: "Leading PM program in Brazil — professors from Netflix, Wildlife Studios, Nubank." },
    { school: "UEM, Brazil", degree: "Master's in Economics", year: "2016", note: "Quantitative economics and policy research." },
    { school: "Gordon College, USA", degree: "Bachelor's in Economics", year: "2013", note: "Econometrics and data analysis. Clarendon Scholar (full scholarship for inner‑city students)." },
  ],

  posts: [
    {
      year: "2026",
      date: "Mar 12",
      title: "Distribution as product — building Tapcheck Express",
      excerpt: "How I led Tapcheck Express — an embedded EWA platform that turned every payroll, HR, and time-and-attendance provider into a Tapcheck distribution channel.",
      tag: "Embedded fintech",
      href: "writing/tapcheck-express.html",
    },
    {
      year: "2025",
      date: "Nov 04",
      title: "Sustainable growth for a flagship product",
      excerpt: "How we lifted trial conversion by 35%, moved WAU from 59% to 75%, and pushed collaboration up 27% on the investment tools at CB Insights.",
      tag: "Growth",
      href: "writing/cb-insights-growth.html",
    },
    {
      year: "2025",
      date: "Aug 21",
      title: "From Maringá to Y-Combinator",
      excerpt: "How a geomarketing consultancy in the interior of Brazil became a B2B software platform serving Cargill, Bunge, and AB InBev — and got into YC along the way.",
      tag: "Founder",
      href: "writing/maringa-yc.html",
    },
  ],
};
